#lang racket
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Not enough money!"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops) "Cops were called!")
  (define failed-attempts 0)
  (define (dispatch pass m)
    (let ([limit 7])
      (if (not (eq? pass password))
          (begin (set! failed-attempts (+ failed-attempts 1))
                 (if (>= failed-attempts limit)
                     (call-the-cops)
                     "Wrong password!"))
          (begin (set! failed-attempts 0)
                 (cond ((eq? m 'withdraw) withdraw)
                       ((eq? m 'deposit) deposit)
                       (else (error "Undefined call -- MAKE-ACCOUNT" m)))))))
  dispatch)

(provide make-account)